name: 有虫子在机器人身上爬（悲）
description: 选这个帮助 YMB 解决他身上的问题
title: '[Bug?]: '
labels: [ "Bug?" ]
assignees: [ "ltzXiaoYanMo" ]

body:
  - type: markdown
    attributes:
      value: |
        ## 感谢您愿意花一些时间来填写这个内容！
        ## 以下是一些注意事项，请务必阅读让我能够更容易处理

        ### ❗ | 确定没有相同问题的ISSUE已被提出。
        ### ❔ | 截图完整聊天记录，尽量完整，不断章取义
        ### ⚠ | 如果涉及个人信息，请自行打码

        ## 如果您不知道如何有效、精准地表述，我建议您先阅读《提问的智慧》
        链接: [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)
        ---
  - type: checkboxes
    id: terms
    attributes:
      label: 请确保您已阅读以上注意事项，并勾选下方的确认框。
      options:
        - label: "我已经仔细阅读上述教程和 [\"《提问的智慧》\"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。"
          required: true
        - label: "我确定这不是因为操作失误而引起的问题。"
          required: true
        - label: "我确定这是一个有意义的Issue，且目前没有解决方案。"
          required: true
        - label: "我已熟读并背诵[文档](https://bot.ymbit.cn)。"
          required: true
  - type: markdown
    attributes:
      value: |
        ## 相关信息
        请根据实际使用环境修改以下信息。


  # Input | Reproduce
  - type: textarea
    id: reproduce-steps
    attributes:
      label: 重现步骤
      description: |
        我需要执行哪些操作才能让 bug 出现？
        简洁清晰的重现步骤能够帮助我更迅速地定位问题所在。
    validations:
      required: true

  # Input | Expected result
  - type: textarea
    id: expected
    attributes:
      label: 期望的结果是什么？
    validations:
      required: true

  # Input | Actual result
  - type: textarea
    id: actual
    attributes:
      label: 实际的结果是什么？
    validations:
      required: true


  # Optional | Extra description
  - type: textarea
    id: extra-desc
    attributes:
      label: 补充说明（可选）

  - type: textarea
    id: img
    attributes:
      label: 来点色图
      description: |
        如果你不提供色图而你的issue中又有其他不符合标准的地方，那么你的issue可能会被直接删除
        括弧：什么离谱玩意（
        不过说实话比起色图我更想看Memes（
        （当然你不放色图/Memes你的Issue也不会被删除，除非你写得真的太sb了）
      value: |
        任何色图终将绳之以法，和蔼！
